SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `types`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `types` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `subject` VARCHAR(255) NULL ,
  `body` TEXT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emails`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `emails` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `typeId` INT NOT NULL ,
  `email` VARCHAR(455) NOT NULL ,
  `sent` TINYINT(1) NULL DEFAULT 0 ,
  `params` VARCHAR(1000) NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `fk_emails_types_idx` (`typeId` ASC) ,
  CONSTRAINT `fk_emails_types`
    FOREIGN KEY (`typeId` )
    REFERENCES `types` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `types` (`id`, `subject`, `body`) VALUES
(1, 'Email of Type 1', '<h1>This is the body of the type 1 Email.</h1>\r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque feugiat dapibus vehicula. Proin euismod metus eu orci eleifend pellentesque. Nullam quam nibh, venenatis vitae vestibulum ut, posuere et orci. Nulla mattis aliquet tortor vitae egestas. Ut iaculis libero eget leo congue porta et sed erat. Donec vulputate ipsum in augue tristique id vulputate sapien pharetra. Morbi rhoncus, est convallis lobortis facilisis, purus sapien luctus eros, fermentum elementum mi diam in diam. Morbi sit amet fermentum erat. Nulla consectetur laoreet sagittis. Phasellus vel dolor quis ligula lacinia sodales.\r\n\r\nCras aliquam nulla eget dolor semper sit amet dignissim velit tempus. Praesent augue nunc, faucibus ut commodo quis, condimentum sit amet odio. Fusce ullamcorper elit ac justo vulputate sed consequat lacus dictum. In at ante sapien, a lacinia mauris. Pellentesque blandit dapibus ligula. Suspendisse non nisl velit, sed tincidunt enim. Nunc a urna non turpis tincidunt fermentum a non dui. Praesent lobortis turpis quis est consequat eget pretium arcu bibendum.\r\n\r\nDonec tristique cursus semper. Ut suscipit accumsan leo, et gravida nunc laoreet vitae. Praesent accumsan dignissim orci at lobortis. Proin vel augue metus. Duis in augue in arcu posuere suscipit. In sit amet dui enim. Aliquam vel tellus vitae ante viverra adipiscing. Phasellus imperdiet eros at diam aliquam faucibus. Pellentesque vestibulum sapien eu tellus pulvinar aliquet. Aenean consectetur sem fringilla metus fermentum eu tempor urna lacinia. Donec mattis purus sed elit ullamcorper quis pretium libero tempor. Aliquam ac pellentesque quam. Nulla aliquet nunc ac turpis auctor laoreet feugiat lorem vehicula. Donec elit leo, adipiscing in mattis id, ultricies eu leo. \r\n\r\n'),
(2, 'Email of Type 2', '<h1>This is the body of the type 2 Email.</h1>\r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque feugiat dapibus vehicula. Proin euismod metus eu orci eleifend pellentesque. Nullam quam nibh, venenatis vitae vestibulum ut, posuere et orci. Nulla mattis aliquet tortor vitae egestas. Ut iaculis libero eget leo congue porta et sed erat. Donec vulputate ipsum in augue tristique id vulputate sapien pharetra. Morbi rhoncus, est convallis lobortis facilisis, purus sapien luctus eros, fermentum elementum mi diam in diam. Morbi sit amet fermentum erat. Nulla consectetur laoreet sagittis. Phasellus vel dolor quis ligula lacinia sodales.\r\n\r\nCras aliquam nulla eget dolor semper sit amet dignissim velit tempus. Praesent augue nunc, faucibus ut commodo quis, condimentum sit amet odio. Fusce ullamcorper elit ac justo vulputate sed consequat lacus dictum. In at ante sapien, a lacinia mauris. Pellentesque blandit dapibus ligula. Suspendisse non nisl velit, sed tincidunt enim. Nunc a urna non turpis tincidunt fermentum a non dui. Praesent lobortis turpis quis est consequat eget pretium arcu bibendum.\r\n\r\nDonec tristique cursus semper. Ut suscipit accumsan leo, et gravida nunc laoreet vitae. Praesent accumsan dignissim orci at lobortis. Proin vel augue metus. Duis in augue in arcu posuere suscipit. In sit amet dui enim. Aliquam vel tellus vitae ante viverra adipiscing. Phasellus imperdiet eros at diam aliquam faucibus. Pellentesque vestibulum sapien eu tellus pulvinar aliquet. Aenean consectetur sem fringilla metus fermentum eu tempor urna lacinia. Donec mattis purus sed elit ullamcorper quis pretium libero tempor. Aliquam ac pellentesque quam. Nulla aliquet nunc ac turpis auctor laoreet feugiat lorem vehicula. Donec elit leo, adipiscing in mattis id, ultricies eu leo. \r\n\r\n'),
(3, 'Email of Type 3', '<h1>This is the body of the type 3 Email.</h1>\r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque feugiat dapibus vehicula. Proin euismod metus eu orci eleifend pellentesque. Nullam quam nibh, venenatis vitae vestibulum ut, posuere et orci. Nulla mattis aliquet tortor vitae egestas. Ut iaculis libero eget leo congue porta et sed erat. Donec vulputate ipsum in augue tristique id vulputate sapien pharetra. Morbi rhoncus, est convallis lobortis facilisis, purus sapien luctus eros, fermentum elementum mi diam in diam. Morbi sit amet fermentum erat. Nulla consectetur laoreet sagittis. Phasellus vel dolor quis ligula lacinia sodales.\r\n\r\nCras aliquam nulla eget dolor semper sit amet dignissim velit tempus. Praesent augue nunc, faucibus ut commodo quis, condimentum sit amet odio. Fusce ullamcorper elit ac justo vulputate sed consequat lacus dictum. In at ante sapien, a lacinia mauris. Pellentesque blandit dapibus ligula. Suspendisse non nisl velit, sed tincidunt enim. Nunc a urna non turpis tincidunt fermentum a non dui. Praesent lobortis turpis quis est consequat eget pretium arcu bibendum.\r\n\r\nDonec tristique cursus semper. Ut suscipit accumsan leo, et gravida nunc laoreet vitae. Praesent accumsan dignissim orci at lobortis. Proin vel augue metus. Duis in augue in arcu posuere suscipit. In sit amet dui enim. Aliquam vel tellus vitae ante viverra adipiscing. Phasellus imperdiet eros at diam aliquam faucibus. Pellentesque vestibulum sapien eu tellus pulvinar aliquet. Aenean consectetur sem fringilla metus fermentum eu tempor urna lacinia. Donec mattis purus sed elit ullamcorper quis pretium libero tempor. Aliquam ac pellentesque quam. Nulla aliquet nunc ac turpis auctor laoreet feugiat lorem vehicula. Donec elit leo, adipiscing in mattis id, ultricies eu leo. \r\n\r\n'),
(4, 'Email of Type 4', '<h1>This is the body of the type 4 Email.</h1>\r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque feugiat dapibus vehicula. Proin euismod metus eu orci eleifend pellentesque. Nullam quam nibh, venenatis vitae vestibulum ut, posuere et orci. Nulla mattis aliquet tortor vitae egestas. Ut iaculis libero eget leo congue porta et sed erat. Donec vulputate ipsum in augue tristique id vulputate sapien pharetra. Morbi rhoncus, est convallis lobortis facilisis, purus sapien luctus eros, fermentum elementum mi diam in diam. Morbi sit amet fermentum erat. Nulla consectetur laoreet sagittis. Phasellus vel dolor quis ligula lacinia sodales.\r\n\r\nCras aliquam nulla eget dolor semper sit amet dignissim velit tempus. Praesent augue nunc, faucibus ut commodo quis, condimentum sit amet odio. Fusce ullamcorper elit ac justo vulputate sed consequat lacus dictum. In at ante sapien, a lacinia mauris. Pellentesque blandit dapibus ligula. Suspendisse non nisl velit, sed tincidunt enim. Nunc a urna non turpis tincidunt fermentum a non dui. Praesent lobortis turpis quis est consequat eget pretium arcu bibendum.\r\n\r\nDonec tristique cursus semper. Ut suscipit accumsan leo, et gravida nunc laoreet vitae. Praesent accumsan dignissim orci at lobortis. Proin vel augue metus. Duis in augue in arcu posuere suscipit. In sit amet dui enim. Aliquam vel tellus vitae ante viverra adipiscing. Phasellus imperdiet eros at diam aliquam faucibus. Pellentesque vestibulum sapien eu tellus pulvinar aliquet. Aenean consectetur sem fringilla metus fermentum eu tempor urna lacinia. Donec mattis purus sed elit ullamcorper quis pretium libero tempor. Aliquam ac pellentesque quam. Nulla aliquet nunc ac turpis auctor laoreet feugiat lorem vehicula. Donec elit leo, adipiscing in mattis id, ultricies eu leo. \r\n\r\n'),
(5, 'Email of Type 5', '<h1>This is the body of the type 5 Email.</h1>\r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque feugiat dapibus vehicula. Proin euismod metus eu orci eleifend pellentesque. Nullam quam nibh, venenatis vitae vestibulum ut, posuere et orci. Nulla mattis aliquet tortor vitae egestas. Ut iaculis libero eget leo congue porta et sed erat. Donec vulputate ipsum in augue tristique id vulputate sapien pharetra. Morbi rhoncus, est convallis lobortis facilisis, purus sapien luctus eros, fermentum elementum mi diam in diam. Morbi sit amet fermentum erat. Nulla consectetur laoreet sagittis. Phasellus vel dolor quis ligula lacinia sodales.\r\n\r\nCras aliquam nulla eget dolor semper sit amet dignissim velit tempus. Praesent augue nunc, faucibus ut commodo quis, condimentum sit amet odio. Fusce ullamcorper elit ac justo vulputate sed consequat lacus dictum. In at ante sapien, a lacinia mauris. Pellentesque blandit dapibus ligula. Suspendisse non nisl velit, sed tincidunt enim. Nunc a urna non turpis tincidunt fermentum a non dui. Praesent lobortis turpis quis est consequat eget pretium arcu bibendum.\r\n\r\nDonec tristique cursus semper. Ut suscipit accumsan leo, et gravida nunc laoreet vitae. Praesent accumsan dignissim orci at lobortis. Proin vel augue metus. Duis in augue in arcu posuere suscipit. In sit amet dui enim. Aliquam vel tellus vitae ante viverra adipiscing. Phasellus imperdiet eros at diam aliquam faucibus. Pellentesque vestibulum sapien eu tellus pulvinar aliquet. Aenean consectetur sem fringilla metus fermentum eu tempor urna lacinia. Donec mattis purus sed elit ullamcorper quis pretium libero tempor. Aliquam ac pellentesque quam. Nulla aliquet nunc ac turpis auctor laoreet feugiat lorem vehicula. Donec elit leo, adipiscing in mattis id, ultricies eu leo. \r\n\r\n');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
